# Site settings
title: Michael Técourt
description: >
  Keep it simple, no-nonsense.
baseurl: ""
url: "https://michaeltecourt.github.io"
twitter_username: michaeltecourt
github_username:  michaeltecourt

# Build settings
markdown: kramdown

timezone: Europe/Paris

plugins:
  - jekyll-redirect-from
