# Site settings
title: Michael Tecourt
description: > # this means to ignore newlines until "baseurl:"
  Keep it simple, no-nonsense.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michaeltecourt.github.io" # the base hostname & protocol for your site
twitter_username: michaeltecourt
github_username:  michaeltecourt

# Build settings
markdown: kramdown

timezone: Europe/Paris

plugins:
  - jekyll-redirect-from
